export const RECEIVE_MUSICS = 'RECEIVE_MUSICS';
export const ACTIVE_ITEM = 'ACTIVE_ITEM';
export const CHANGE_DID_INVALIDATE = 'CHANGE_DID_INVALIDATE';
export const RECEIVE_PLAYLIST_DETAIL = 'RECEIVE_PLAYLIST_DETAIL';
export const CHANGE_CURRENT_PLAY = 'CHANGE_CURRENT_PLAY'